apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: multi-everything
  labels:
    app: analytics-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
        version: v1
    spec:
      containers:
      - name: analytics-service
        #image: multi-everything/analytics-service:latest
        image: ajadocker/analytics-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: multi-everything
spec:
  selector:
    app: analytics-service
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP