apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  namespace: multi-everything
  labels:
    app: content-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
        version: v1
    spec:
      containers:
      - name: content-api
        #image: multi-everything/content-api:latest
        image: ajadocker/content-api:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: host
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: content-api-service
  namespace: multi-everything
spec:
  selector:
    app: content-api
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP