apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: content-api:local
        imagePullPolicy: Never
        ports:
        - containerPort: 80
