apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: multi-everything
type: Opaque
data:
  host: ZGIubXVsdGktZXZlcnl0aGluZy5sb2NhbA==  # db.multi-everything.local
  username: bXVsdGlldmVyeXRoaW5nX2FkbWlu     # multieverything_admin
  password: dGVtcF9wYXNzd29yZF8xMjM=         # temp_password_123
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: multi-everything
type: Opaque
data:
  openai-api-key: ZHVtbXkta2V5LWZvci1ub3c=   # dummy-key-for-now
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXk=   # super-secret-jwt-key
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: multi-everything
type: Opaque
data:
  password: cmVkaXMtcGFzc3dvcmQxMjM=         # redis-password123